"""full datetime

Revision ID: 144649a54955
Revises: 305ace38cf61
Create Date: 2015-10-15 15:03:12.623726

"""

# revision identifiers, used by Alembic.
revision = '144649a54955'
down_revision = '305ace38cf61'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'created_at', type_=mysql.DATETIME(fsp=6), nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'created_at', type_=mysql.DATETIME(fsp=6), nullable=True)
    ### end Alembic commands ###
