"""public media flag

Revision ID: 4684e5c6151a
Revises: 5490cd75510e
Create Date: 2015-08-31 20:38:05.380800

"""

# revision identifiers, used by Alembic.
revision = '4684e5c6151a'
down_revision = '5490cd75510e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('is_public', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'is_public')
    ### end Alembic commands ###
